### ISSUE TITLE
Getting error: CUDA is not available

### ISSUE THREAD

**Issue by harshitajmani** [joaopcm1996/notebooks#1]
# Getting this error when creating an endpoint in sagemaker

`2024-03-19T16:31:57.748653Z  INFO download: lorax_launcher: Successfully downloaded weights.
2024-03-19T16:31:57.748840Z  INFO shard-manager: lorax_launcher: Starting shard rank=0
2024-03-19T16:32:01.362713Z ERROR lorax_launcher: server.py:273 Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/lorax-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/server.py", line 317, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.10/site-packages/lorax_server/server.py", line 269, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/__init__.py", line 179, in get_model
    from lorax_server.models.flash_mistral import FlashMistral
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/flash_mistral.py", line 21, in <module>
    from lorax_server.models.custom_modeling.flash_mistral_modeling import (
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/custom_modeling/flash_mistral_modeling.py", line 32, in <module>
    from lorax_server.utils.flash_attn import HAS_FLASH_ATTN_V2
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/utils/flash_attn.py", line 10, in <module>
    raise ImportError("CUDA is not available")
ImportError: CUDA is not available

2024-03-19T16:32:02.153071Z ERROR shard-manager: lorax_launcher: Shard complete standard error output:

/opt/conda/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Traceback (most recent call last):

  File "/opt/conda/bin/lorax-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/cli.py", line 89, in serve
    server.serve(

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/server.py", line 317, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/server.py", line 269, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/__init__.py", line 179, in get_model
    from lorax_server.models.flash_mistral import FlashMistral

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/flash_mistral.py", line 21, in <module>
    from lorax_server.models.custom_modeling.flash_mistral_modeling import (

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/custom_modeling/flash_mistral_modeling.py", line 32, in <module>
    from lorax_server.utils.flash_attn import HAS_FLASH_ATTN_V2

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/utils/flash_attn.py", line 10, in <module>
    raise ImportError("CUDA is not available")

ImportError: CUDA is not available
 rank=0
2024-03-19T16:32:02.252292Z ERROR lorax_launcher: Shard 0 failed to start
2024-03-19T16:32:02.252322Z  INFO lorax_launcher: Shutting down shards
Error: ShardCannotStart`

**Comment by joaopcm1996** [comment]
seems to be an issue with lorax 0.8.1 that I haven't looked into, just pushed a change to fix on version 0.8.0, please retry with this

**Comment by harshitajmani** [comment]
It worked. Thank you @joaopcm1996

**Comment by yash11021** [comment]
I came across this same issue today! Thanks for the clarification @joaopcm1996

**Comment by yash11021** [comment]
@joaopcm1996 Question for you if you get a second - I'm running a training job using the JumpStartEstimator which stores lora weights in s3 as .safetensor files. Then, in attempting to reference the adapter weights in my payload to the Predictor object which is pointing to my deployed base model endpoint (pulling in LoRAX), I get an error where the Predictor is expecting .bin files. Have you come across this?

**Comment by joaopcm1996** [comment]
To clarify on the above, the issue is not on LoRAX, seems to be an issue with NVIDIA driver version on SM Endpoints. 

@yash11021 I have not run into this, I think LoRAX should accept .safetensor format.
